### ISSUE TITLE
How can I fix a typo in pdf file?

### ISSUE THREAD

**Issue by jaeyoo** [JackHidary/quantumcomputingbook#14]
Can I get LaTeX format of them?

For example, in chapter02.pdf, the problem 1. says "Divicenzo criteria", but the correct term is ["DiVincenzo's criteria"](https://en.wikipedia.org/wiki/DiVincenzo%27s_criteria)

**Comment by rmlarose** [comment]
For now only the pdf versions of problem sets will be made available as the tex source also contains solutions. For typos/suggested changes, an issue like this works or email to Jack Hidary. Unfortunately the work won't show up on GitHub but it will be otherwise acknowledged!

I'll fix this typo and close this issue once the new version has been posted.
